#spring:
#  cloud:
#    azure:
#      active-directory:
#        enabled: true
#  security:
#    oauth2:
#      client:
#        registration:
#          azure:
#
#            client-id: c0b1d6a3-4c63-4c06-94b9-daac46b4891c
#            client-secret: .Vt8Q~iBZ2IgeKFiwKGpU7JeepEZicJLzPQLudo~
#            scope: openid, profile, email
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/
#            client-name: azure
#
#        provider:
#          azure:
#            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/v1.0/me
#            user-name-attribute: displayName
#            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
logging:
  level:
    org.springframework.security: DEBUG
    root: warn
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.azure: DEBUG
